export const SET_TASK_FORM = 'TASK/SET_TASK_FORM';

export const ADD_TASK = 'TASK/ADD_TASK';
export const ADD_TASK_SUCCESS = 'TASK/ADD_TASK_SUCCESS';
export const ADD_TASK_FAILED = 'TASK/ADD_TASK_FAILED';

export const REMOVE_TASK = 'TASK/REMOVE_TASK';
export const REMOVE_TASK_SUCCESS = 'TASK/REMOVE_TASK_SUCCESS';
export const REMOVE_TASK_FAILED = 'TASK/REMOVE_TASK_FAILED';

export const SET_TASK_LIST = 'TASK/SET_TASK_LIST';
export const SET_TASK_LIST_SUCCESS = 'TASK/SET_TASK_LIST_SUCCESS';
export const SET_TASK_LIST_FAILED = 'TASK/SET_TASK_LIST_FAILED';

export const UPDATE_TASK = 'TASK/UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'TASK/UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILED = 'TASK/UPDATE_TASK_FAILED';
